# Three opt-in helm releases:
#   - aws-load-balancer-controller (needs IAM via EKS Pod Identity)
#   - ingress-nginx (no AWS IAM)
#   - cert-manager (no AWS IAM unless you enable Route53 DNS-01)

locals {
  aws_lb_controller_sa = "aws-load-balancer-controller"
}

# ── AWS Load Balancer Controller: IAM via Pod Identity ──────────────────
#
# Role trust = `pods.eks.amazonaws.com` (no OIDC dependency).
# Policy = AWSLoadBalancerControllerIAMPolicy generated by the upstream
# iam-role-for-service-accounts module (`attach_load_balancer_controller_policy`).
# OIDC inputs left empty since this role isn't used for IRSA.
module "aws_lb_controller_role" {
  count  = var.enable_aws_lb_controller ? 1 : 0
  source = "../../../template/modules/mod-aws-iam-role/v1.1.0/modules/iam-role-for-service-accounts"

  name                                   = "${var.company}-${var.project}-lbctrl-${var.service_name}-${var.environment}"
  policy_name                            = "aws-load-balancer-controller"
  attach_load_balancer_controller_policy = true
  oidc_providers                         = {}
  override_trust_policy_documents = [
    jsonencode({
      Version = "2012-10-17"
      Statement = [{
        Effect    = "Allow"
        Principal = { Service = "pods.eks.amazonaws.com" }
        Action    = ["sts:AssumeRole", "sts:TagSession"]
      }]
    })
  ]
}

resource "aws_eks_pod_identity_association" "aws_lb_controller" {
  count           = var.enable_aws_lb_controller ? 1 : 0
  cluster_name    = var.cluster_name
  namespace       = var.aws_lb_controller_namespace
  service_account = local.aws_lb_controller_sa
  role_arn        = module.aws_lb_controller_role[0].arn
}

# ── aws-load-balancer-controller helm release ───────────────────────────
resource "helm_release" "aws_lb_controller" {
  count = var.enable_aws_lb_controller ? 1 : 0

  name             = "${var.company}-${var.project}-lbctrl-${var.service_name}-${var.environment}"
  namespace        = var.aws_lb_controller_namespace
  create_namespace = false
  repository       = "https://aws.github.io/eks-charts"
  chart            = "aws-load-balancer-controller"
  version          = var.aws_lb_controller_chart_version
  replace          = true
  force_update     = true
  cleanup_on_fail  = true

  values = [
    templatefile("./values/aws-load-balancer-controller.yaml", {
      cluster_name    = var.cluster_name
      service_account = local.aws_lb_controller_sa
      vpc_id = var.aws_lb_controller.vpc_id
      region = var.aws_lb_controller.region
    })
  ]

  depends_on = [aws_eks_pod_identity_association.aws_lb_controller]
}

# ── nginx-ingress ───────────────────────────────────────────────────────
resource "helm_release" "nginx_ingress" {
  count = var.enable_nginx_ingress ? 1 : 0

  name             = "${var.company}-${var.project}-nginx-${var.service_name}-${var.environment}"
  namespace        = var.nginx_ingress_namespace
  create_namespace = true
  repository       = "https://kubernetes.github.io/ingress-nginx"
  chart            = "ingress-nginx"
  version          = var.nginx_ingress_chart_version
  replace          = true
  force_update     = true
  cleanup_on_fail  = true

  values = [file("./values/nginx-ingress.yaml")]
}

# ── cert-manager ────────────────────────────────────────────────────────
resource "helm_release" "cert_manager" {
  count = var.enable_cert_manager ? 1 : 0

  name             = "${var.company}-${var.project}-cm-${var.service_name}-${var.environment}"
  namespace        = var.cert_manager_namespace
  create_namespace = true
  repository       = "https://charts.jetstack.io"
  chart            = "cert-manager"
  version          = var.cert_manager_chart_version
  replace          = true
  force_update     = true
  cleanup_on_fail  = true

  values = [file("./values/cert-manager.yaml")]

  set = [{
    name  = "installCRDs"
    value = "true"
  }]
}
